#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.42000
=======
//     Runtime Version:4.0.30319.34209
>>>>>>> toStrings_null
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
    using Signum.Engine.Mailing;
    
    #line default
    #line hidden
    using Signum.Entities;
    
<<<<<<< HEAD
    #line 4 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
    using Signum.Entities.DynamicQuery;
    
    #line default
    #line hidden
    
=======
>>>>>>> toStrings_null
    #line 1 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
    using Signum.Entities.Mailing;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 3 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
    using Signum.Web.Mailing;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Mailing/Views/AsyncEmailSenderDashboard.cshtml")]
<<<<<<< HEAD
    public partial class _Mailing_Views_AsyncEmailSenderDashboard_cshtml : System.Web.Mvc.WebViewPage<AsyncEmailSenderState>
=======
    public partial class _Mailing_Views_AsyncEmailSenderDashboard_cshtml : System.Web.Mvc.WebViewPage<EmailAsyncProcessState>
>>>>>>> toStrings_null
    {
        public _Mailing_Views_AsyncEmailSenderDashboard_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"emailAsyncMainDiv\"");

<<<<<<< HEAD
WriteLiteral(">\r\n    <h2>Async Email Sender State</h2>\r\n    <div>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 246), Tuple.Create("\"", 311)
            
            #line 9 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
, Tuple.Create(Tuple.Create("", 253), Tuple.Create<System.Object, System.Int32>(Url.Action<AsyncEmailSenderController>(pc => pc.Stop())
            
            #line default
            #line hidden
, 253), false)
=======
WriteLiteral(">\r\n    <h2>Email Async Sender state</h2>\r\n    <div>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 210), Tuple.Create("\"", 275)
            
            #line 8 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
, Tuple.Create(Tuple.Create("", 217), Tuple.Create<System.Object, System.Int32>(Url.Action<AsyncEmailSenderController>(pc => pc.Stop())
            
            #line default
            #line hidden
, 217), false)
>>>>>>> toStrings_null
);

WriteLiteral(" class=\"sf-button btn btn-default active\"");

<<<<<<< HEAD
WriteAttribute("style", Tuple.Create(" style=\"", 353), Tuple.Create("\"", 409)
            
            #line 9 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                                               , Tuple.Create(Tuple.Create("", 361), Tuple.Create<System.Object, System.Int32>(Model.Running ? "" : "display:none"
            
            #line default
            #line hidden
, 361), false)
, Tuple.Create(Tuple.Create("", 399), Tuple.Create(";color:red", 399), true)
=======
WriteAttribute("style", Tuple.Create(" style=\"", 317), Tuple.Create("\"", 373)
            
            #line 8 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                                               , Tuple.Create(Tuple.Create("", 325), Tuple.Create<System.Object, System.Int32>(Model.Running ? "" : "display:none"
            
            #line default
            #line hidden
, 325), false)
, Tuple.Create(Tuple.Create("", 363), Tuple.Create(";color:red", 363), true)
>>>>>>> toStrings_null
);

WriteLiteral(" id=\"sfEmailAsyncProcessDisable\"");

WriteLiteral(">Stop </a>\r\n        <a");

<<<<<<< HEAD
WriteAttribute("href", Tuple.Create(" href=\"", 464), Tuple.Create("\"", 530)
            
            #line 10 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
, Tuple.Create(Tuple.Create("", 471), Tuple.Create<System.Object, System.Int32>(Url.Action<AsyncEmailSenderController>(pc => pc.Start())
            
            #line default
            #line hidden
, 471), false)
=======
WriteAttribute("href", Tuple.Create(" href=\"", 428), Tuple.Create("\"", 494)
            
            #line 9 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
, Tuple.Create(Tuple.Create("", 435), Tuple.Create<System.Object, System.Int32>(Url.Action<AsyncEmailSenderController>(pc => pc.Start())
            
            #line default
            #line hidden
, 435), false)
>>>>>>> toStrings_null
);

WriteLiteral(" class=\"sf-button btn btn-default\"");

<<<<<<< HEAD
WriteAttribute("style", Tuple.Create(" style=\"", 565), Tuple.Create("\"", 612)
            
            #line 10 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                                         , Tuple.Create(Tuple.Create("", 573), Tuple.Create<System.Object, System.Int32>(!Model.Running ? "" : "display:none"
            
            #line default
            #line hidden
, 573), false)
=======
WriteAttribute("style", Tuple.Create(" style=\"", 529), Tuple.Create("\"", 576)
            
            #line 9 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                                         , Tuple.Create(Tuple.Create("", 537), Tuple.Create<System.Object, System.Int32>(!Model.Running ? "" : "display:none"
            
            #line default
            #line hidden
, 537), false)
>>>>>>> toStrings_null
);

WriteLiteral(" id=\"sfEmailAsyncProcessEnable\"");

WriteLiteral(">Start </a>\r\n    </div>\r\n\r\n    <div>\r\n        <br />\r\n        State: <strong>\r\n");

            
<<<<<<< HEAD
            #line 16 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 15 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
            
            
            #line default
            #line hidden
            
<<<<<<< HEAD
            #line 16 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 15 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
             if (Model.Running)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" style=\"color: green\"");

WriteLiteral(">RUNNING</span>\r\n");

            
<<<<<<< HEAD
            #line 19 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 18 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">STOPPED</span>\r\n");

            
<<<<<<< HEAD
            #line 23 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 22 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
            }

            
            #line default
            #line hidden
WriteLiteral("        </strong>\r\n        <br />\r\n        CurrentProcessIdentifier: ");

            
<<<<<<< HEAD
            #line 26 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 25 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
                             Write(Model.CurrentProcessIdentifier);

            
            #line default
            #line hidden
<<<<<<< HEAD
WriteLiteral("\r\n        <br />\r\n        AsyncSenderPeriod: ");

            
            #line 28 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                      Write(Model.AsyncSenderPeriod);
=======
WriteLiteral("\r\n        <br />\r\n        DelayBetweenProcessesMilliseconds: ");

            
            #line 27 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                                      Write(Model.DelayBetweenProcessesMilliseconds);
>>>>>>> toStrings_null

            
            #line default
            #line hidden
<<<<<<< HEAD
WriteLiteral(" sec\r\n        <br />\r\n        NextPlannedExecution: ");

            
            #line 30 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
WriteLiteral("\r\n        <br />\r\n        NextPlannedExecution: ");

            
            #line 29 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
                         Write(Model.NextPlannedExecution);

            
            #line default
            #line hidden
<<<<<<< HEAD
WriteLiteral(" (");

            
            #line 30 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
                                                       Write(Model.NextPlannedExecution == null ? "-None-" : Model.NextPlannedExecution.Value.ToAgoString());

            
            #line default
            #line hidden
WriteLiteral(")\r\n        <br />\r\n        IsCancelationRequested: ");

            
            #line 32 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
WriteLiteral("\r\n        <br />\r\n        IsCancelationRequested: ");

            
            #line 31 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
                           Write(Model.IsCancelationRequested);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br />\r\n        QueuedItems: ");

            
<<<<<<< HEAD
            #line 34 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 33 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
                Write(Model.QueuedItems);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br />\r\n        MachineName: ");

            
<<<<<<< HEAD
            #line 36 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 35 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
                Write(Model.MachineName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br />\r\n        ApplicationName: ");

            
<<<<<<< HEAD
            #line 38 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 37 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
                    Write(Model.ApplicationName);

            
            #line default
            #line hidden
<<<<<<< HEAD
WriteLiteral("\r\n    </div>\r\n    <br />\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
Write(Html.SearchControl(new FindOptions(typeof(EmailMessageEntity))
{
    OrderOptions = { new OrderOption("Entity.CreationDate", OrderType.Descending) },
    ShowFilters = false,
    SearchOnLoad = true,
    Pagination = new Pagination.Firsts(10),
}, new Context(null, "em")));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n");
=======
WriteLiteral("\r\n    </div>\r\n    <script>\r\n        $(function () {\r\n");
>>>>>>> toStrings_null

WriteLiteral("            ");

            
<<<<<<< HEAD
            #line 51 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
=======
            #line 41 "..\..\Mailing\Views\AsyncEmailSenderDashboard.cshtml"
>>>>>>> toStrings_null
        Write(MailingClient.AsyncEmailSenderModule["initDashboard"](Url.Action<AsyncEmailSenderController>(p => p.View())));

            
            #line default
            #line hidden
WriteLiteral("\r\n        });\r\n    </script>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
