#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Profiler\Views\TimeTable.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Profiler\Views\TimeTable.cshtml"
    using System.Drawing;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    using Signum.Utilities;
    using Signum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Profiler/Views/TimeTable.cshtml")]
    public partial class _Profiler_Views_TimeTable_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Profiler_Views_TimeTable_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Profiler\Views\TimeTable.cshtml"
    
    ViewBag.Title = "Times table";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"profilerTimesExternalDiv\"");

WriteLiteral(">\r\n    <h3>Times table</h3>\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Profiler\Views\TimeTable.cshtml"
Write(Html.ActionLink("Clear", (Signum.Web.Profiler.ProfilerController a) => a.ClearTimesTable(), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <table");

WriteLiteral(" class=\"table table-nonfluid\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Entity
                </th>
                <th>
                    Executions
                </th>
                <th>
                    Last Time
                </th>
                <th>
                    Min
                </th>
                <th>
                    Average
                </th>
                <th>
                    Max
                </th>
                <th>
                    total
                </th>
            </tr>
        </thead>
");

            
            #line 38 "..\..\Profiler\Views\TimeTable.cshtml"
        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Profiler\Views\TimeTable.cshtml"
           var times = TimeTracker.IdentifiedElapseds;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 39 "..\..\Profiler\Views\TimeTable.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Profiler\Views\TimeTable.cshtml"
         if (times.Count > 0)
        {

            Func<float, string> getColor = f => ColorTranslator.ToHtml(ColorExtensions.Interpolate(Color.FromArgb(255, 255, 255), f, Color.FromArgb(255, 0, 0)));

            var max = new
            {
                Count = (float)times.Values.Max(a => a.Count),
                LastTime = (float)times.Values.Max(a => a.LastTime),
                MinTime = (float)times.Values.Max(a => a.MinTime),
                Average = (float)times.Values.Max(a => a.Average),
                MaxTime = (float)times.Values.Max(a => a.MaxTime),
                TotalTime = (float)times.Values.Max(a => a.TotalTime),
            };

            
            #line default
            #line hidden
WriteLiteral("            <tbody>\r\n");

            
            #line 54 "..\..\Profiler\Views\TimeTable.cshtml"
                
            
            #line default
            #line hidden
            
            #line 54 "..\..\Profiler\Views\TimeTable.cshtml"
                 foreach (var pair in times)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteLiteral(" style=\"background: #FFFFFF\"");

WriteLiteral(">\r\n                        <td>\r\n                            <span");

WriteLiteral(" class=\"processName\"");

WriteLiteral(">");

            
            #line 58 "..\..\Profiler\Views\TimeTable.cshtml"
                                                  Write(pair.Key.TryBefore(' ') ?? pair.Key);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </td>\r\n                        <td>\r\n");

            
            #line 61 "..\..\Profiler\Views\TimeTable.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 61 "..\..\Profiler\Views\TimeTable.cshtml"
                             if (pair.Key.TryAfter(' ') != null)
                            {
            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"entityName\"");

WriteLiteral(">");

            
            #line 62 "..\..\Profiler\Views\TimeTable.cshtml"
                                                 Write(pair.Key.After(' '));

            
            #line default
            #line hidden
WriteLiteral("</span>");

            
            #line 62 "..\..\Profiler\Views\TimeTable.cshtml"
                                                                                 }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                        <td");

WriteAttribute("style", Tuple.Create(" style=\"", 2268), Tuple.Create("\"", 2347)
, Tuple.Create(Tuple.Create("", 2276), Tuple.Create("text-align:center;", 2276), true)
, Tuple.Create(Tuple.Create(" ", 2294), Tuple.Create("background:", 2295), true)
            
            #line 64 "..\..\Profiler\Views\TimeTable.cshtml"
, Tuple.Create(Tuple.Create("", 2306), Tuple.Create<System.Object, System.Int32>(getColor(pair.Value.Count / max.Count)
            
            #line default
            #line hidden
, 2306), false)
, Tuple.Create(Tuple.Create("", 2345), Tuple.Create(";", 2345), true)
, Tuple.Create(Tuple.Create(" ", 2346), Tuple.Create("", 2346), true)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 65 "..\..\Profiler\Views\TimeTable.cshtml"
                       Write(pair.Value.Count);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td");

WriteAttribute("style", Tuple.Create(" style=\"", 2448), Tuple.Create("\"", 2528)
, Tuple.Create(Tuple.Create("", 2456), Tuple.Create("text-align:right;", 2456), true)
, Tuple.Create(Tuple.Create(" ", 2473), Tuple.Create("background:", 2474), true)
            
            #line 67 "..\..\Profiler\Views\TimeTable.cshtml"
, Tuple.Create(Tuple.Create("", 2485), Tuple.Create<System.Object, System.Int32>(getColor(pair.Value.LastTime/max.LastTime)
            
            #line default
            #line hidden
, 2485), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 68 "..\..\Profiler\Views\TimeTable.cshtml"
                   Write(pair.Value.LastTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteAttribute("style", Tuple.Create(" style=\"", 2620), Tuple.Create("\"", 2700)
, Tuple.Create(Tuple.Create("", 2628), Tuple.Create("text-align:right;", 2628), true)
, Tuple.Create(Tuple.Create(" ", 2645), Tuple.Create("background:", 2646), true)
            
            #line 70 "..\..\Profiler\Views\TimeTable.cshtml"
, Tuple.Create(Tuple.Create("", 2657), Tuple.Create<System.Object, System.Int32>(getColor(pair.Value.MinTime / max.MinTime)
            
            #line default
            #line hidden
, 2657), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 71 "..\..\Profiler\Views\TimeTable.cshtml"
               Write(pair.Value.MinTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteAttribute("style", Tuple.Create(" style=\"", 2779), Tuple.Create("\"", 2866)
, Tuple.Create(Tuple.Create("", 2787), Tuple.Create("text-align:right;", 2787), true)
, Tuple.Create(Tuple.Create(" ", 2804), Tuple.Create("background:", 2805), true)
            
            #line 73 "..\..\Profiler\Views\TimeTable.cshtml"
, Tuple.Create(Tuple.Create("", 2816), Tuple.Create<System.Object, System.Int32>(getColor((float)pair.Value.Average / max.Average)
            
            #line default
            #line hidden
, 2816), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 74 "..\..\Profiler\Views\TimeTable.cshtml"
           Write(pair.Value.Average);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td");

WriteAttribute("style", Tuple.Create(" style=\"", 2933), Tuple.Create("\"", 2995)
, Tuple.Create(Tuple.Create("", 2941), Tuple.Create("background:", 2941), true)
            
            #line 76 "..\..\Profiler\Views\TimeTable.cshtml"
, Tuple.Create(Tuple.Create("", 2952), Tuple.Create<System.Object, System.Int32>(getColor(pair.Value.MaxTime / max.MaxTime)
            
            #line default
            #line hidden
, 2952), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 77 "..\..\Profiler\Views\TimeTable.cshtml"
       Write(pair.Value.MaxTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n    <td");

WriteAttribute("style", Tuple.Create(" style=\"", 3050), Tuple.Create("\"", 3134)
, Tuple.Create(Tuple.Create("", 3058), Tuple.Create("text-align:right;", 3058), true)
, Tuple.Create(Tuple.Create(" ", 3075), Tuple.Create("background:", 3076), true)
            
            #line 79 "..\..\Profiler\Views\TimeTable.cshtml"
, Tuple.Create(Tuple.Create("", 3087), Tuple.Create<System.Object, System.Int32>(getColor(pair.Value.TotalTime / max.TotalTime)
            
            #line default
            #line hidden
, 3087), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 80 "..\..\Profiler\Views\TimeTable.cshtml"
   Write(pair.Value.TotalTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n</tr>\r\n");

            
            #line 83 "..\..\Profiler\Views\TimeTable.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n");

            
            #line 85 "..\..\Profiler\Views\TimeTable.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n\r\n</div>");

        }
    }
}
#pragma warning restore 1591
