#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Dashboard\Views\Dashboard.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Signum.Entities;
    
    #line 2 "..\..\Dashboard\Views\Dashboard.cshtml"
    using Signum.Entities.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Views\Dashboard.cshtml"
    using Signum.Entities.UserAssets;
    
    #line default
    #line hidden
    using Signum.Utilities;
    using Signum.Web;
    
    #line 3 "..\..\Dashboard\Views\Dashboard.cshtml"
    using Signum.Web.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Dashboard/Views/Dashboard.cshtml")]
    public partial class _Dashboard_Views_Dashboard_cshtml : System.Web.Mvc.WebViewPage<DashboardDN>
    {
        public _Dashboard_Views_Dashboard_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Dashboard\Views\Dashboard.cshtml"
Write(Html.ScriptCss("~/Dashboard/Content/Dashboard.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

            
            #line 11 "..\..\Dashboard\Views\Dashboard.cshtml"
  
    var currentEntity = (Entity)ViewData["currentEntity"];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"dashboard-container\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Dashboard\Views\Dashboard.cshtml"
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Dashboard\Views\Dashboard.cshtml"
     if (currentEntity != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" style=\"float: right; text-align:right\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"control-panel-title\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Dashboard\Views\Dashboard.cshtml"
                
            
            #line default
            #line hidden
            
            #line 20 "..\..\Dashboard\Views\Dashboard.cshtml"
                 if (Navigator.IsNavigable(currentEntity, null))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"sf-entity-title\"");

WriteAttribute("href", Tuple.Create(" href=\"", 603), Tuple.Create("\"", 649)
            
            #line 22 "..\..\Dashboard\Views\Dashboard.cshtml"
, Tuple.Create(Tuple.Create("", 610), Tuple.Create<System.Object, System.Int32>(Navigator.NavigateRoute(currentEntity)
            
            #line default
            #line hidden
, 610), false)
);

WriteLiteral(">");

            
            #line 22 "..\..\Dashboard\Views\Dashboard.cshtml"
                                                                                         Write(currentEntity.ToString());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 23 "..\..\Dashboard\Views\Dashboard.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"sf-entity-title\"");

WriteLiteral(">");

            
            #line 26 "..\..\Dashboard\Views\Dashboard.cshtml"
                                             Write(currentEntity.ToString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 27 "..\..\Dashboard\Views\Dashboard.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <br />\r\n                <small");

WriteLiteral(" class=\"sf-type-nice-name\"");

WriteLiteral(">");

            
            #line 29 "..\..\Dashboard\Views\Dashboard.cshtml"
                                            Write(Navigator.Manager.GetTypeTitle(currentEntity));

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n            </h3>\r\n        </div>\r\n");

            
            #line 32 "..\..\Dashboard\Views\Dashboard.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 34 "..\..\Dashboard\Views\Dashboard.cshtml"
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Dashboard\Views\Dashboard.cshtml"
     using (Html.BeginForm("DoPostBack", "Signum", "POST"))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2");

WriteLiteral(" class=\"control-panel-title\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Dashboard\Views\Dashboard.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Dashboard\Views\Dashboard.cshtml"
             if (Navigator.IsNavigable(Model, null, isSearch: true))
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1231), Tuple.Create("\"", 1293)
            
            #line 39 "..\..\Dashboard\Views\Dashboard.cshtml"
, Tuple.Create(Tuple.Create("", 1238), Tuple.Create<System.Object, System.Int32>(Navigator.NavigateRoute(typeof(DashboardDN), Model.Id)
            
            #line default
            #line hidden
, 1238), false)
);

WriteLiteral(">");

            
            #line 39 "..\..\Dashboard\Views\Dashboard.cshtml"
                                                                             Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 40 "..\..\Dashboard\Views\Dashboard.cshtml"
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 43 "..\..\Dashboard\Views\Dashboard.cshtml"
           Write(Model.DisplayName);

            
            #line default
            #line hidden
            
            #line 43 "..\..\Dashboard\Views\Dashboard.cshtml"
                                  
            }

            
            #line default
            #line hidden
WriteLiteral("        </h2>\r\n");

            
            #line 46 "..\..\Dashboard\Views\Dashboard.cshtml"



            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"dashboard-container-inner\"");

WriteLiteral(">\r\n\r\n");

            
            #line 50 "..\..\Dashboard\Views\Dashboard.cshtml"
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Dashboard\Views\Dashboard.cshtml"
               
                Html.RenderPartial(DashboardClient.ViewPrefix.Formato("DashboardView"), Model);
            
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 54 "..\..\Dashboard\Views\Dashboard.cshtml"
            
            
            #line default
            #line hidden
            
            #line 54 "..\..\Dashboard\Views\Dashboard.cshtml"
             if (Model.AutoRefreshPeriod != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                    $(function () {\r\n                        setTimeout(functi" +
"on () {\r\n                            window.location.href = window.location.href" +
";\r\n                        }, ");

            
            #line 60 "..\..\Dashboard\Views\Dashboard.cshtml"
                       Write(Model.AutoRefreshPeriod.Value * 1000);

            
            #line default
            #line hidden
WriteLiteral(");\r\n                    });\r\n                </script>\r\n");

            
            #line 63 "..\..\Dashboard\Views\Dashboard.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 65 "..\..\Dashboard\Views\Dashboard.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
