#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Cache\Views\Statistics.cshtml"
    using Signum.Engine.Cache;
    
    #line default
    #line hidden
    using Signum.Entities;
    using Signum.Utilities;
    
    #line 1 "..\..\Cache\Views\Statistics.cshtml"
    using Signum.Utilities.ExpressionTrees;
    
    #line default
    #line hidden
    using Signum.Web;
    
    #line 3 "..\..\Cache\Views\Statistics.cshtml"
    using Signum.Web.Cache;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Cache/Views/Statistics.cshtml")]
    public partial class _Cache_Views_Statistics_cshtml : System.Web.Mvc.WebViewPage<List<CachedTableBase>>
    {

#line 44 "..\..\Cache\Views\Statistics.cshtml"
public System.Web.WebPages.HelperResult ShowTree(CachedTableBase table, int depth)
            {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 44 "..\..\Cache\Views\Statistics.cshtml"
            

#line default
#line hidden

#line 45 "..\..\Cache\Views\Statistics.cshtml"
             


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <tr");

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 1525), Tuple.Create("\"", 1669)
, Tuple.Create(Tuple.Create("", 1533), Tuple.Create("opacity:", 1533), true)

#line 46 "..\..\Cache\Views\Statistics.cshtml"
, Tuple.Create(Tuple.Create("", 1541), Tuple.Create<System.Object, System.Int32>(depth == 0 ?  "1":
            depth == 1 ?  ".7" :
            depth == 2 ?  ".5" :
            depth == 3 ?  ".4" : ".3"

#line default
#line hidden
, 1541), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n            <td>\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 51 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, Enumerable.Repeat(" → ", depth).ToString("") + table.Table.Name.Name);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n        </td>\r\n        <td>\r\n");

WriteLiteralTo(__razor_helper_writer, "            ");


#line 54 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, table.Type.TypeName());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    </td>\r\n    <td>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 57 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, table.Count.TryToString() ?? "-- not loaded --");


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n</td>\r\n<td>\r\n");

WriteLiteralTo(__razor_helper_writer, "    ");


#line 60 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, table.Hits.DefaultToNull());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n</td>\r\n<td>\r\n");

WriteLiteralTo(__razor_helper_writer, "    ");


#line 63 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, table.Invalidations.DefaultToNull());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n</td>\r\n<td>\r\n");

WriteLiteralTo(__razor_helper_writer, "    ");


#line 66 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, table.Loads.DefaultToNull());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n</td>\r\n<td>\r\n");

WriteLiteralTo(__razor_helper_writer, "    ");


#line 69 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, table.SumLoadTime.NiceToString());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n</td>\r\n</tr>\r\n");


#line 72 "..\..\Cache\Views\Statistics.cshtml"

if (table.SubTables != null)
{
    foreach (var st in table.SubTables)
    {
            

#line default
#line hidden

#line 77 "..\..\Cache\Views\Statistics.cshtml"
WriteTo(__razor_helper_writer, ShowTree(st, depth + 1));


#line default
#line hidden

#line 77 "..\..\Cache\Views\Statistics.cshtml"
                                    
    }
}


#line default
#line hidden
});

#line 80 "..\..\Cache\Views\Statistics.cshtml"
}
#line default
#line hidden

        public _Cache_Views_Statistics_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"cacheStatisticsExternalDiv\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 7 "..\..\Cache\Views\Statistics.cshtml"
   Write(ViewData[ViewDataKeys.Title]);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n    <div>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 230), Tuple.Create("\"", 286)
            
            #line 9 "..\..\Cache\Views\Statistics.cshtml"
, Tuple.Create(Tuple.Create("", 237), Tuple.Create<System.Object, System.Int32>(Url.Action((CacheController pc) => pc.Disable())
            
            #line default
            #line hidden
, 237), false)
);

WriteLiteral(" class=\"sf-button btn btn-default\"");

WriteAttribute("style", Tuple.Create("\r\n           style=\"", 321), Tuple.Create("\"", 404)
            
            #line 10 "..\..\Cache\Views\Statistics.cshtml"
, Tuple.Create(Tuple.Create("", 341), Tuple.Create<System.Object, System.Int32>(!CacheLogic.GloballyDisabled ? "" : "display:none"
            
            #line default
            #line hidden
, 341), false)
, Tuple.Create(Tuple.Create("", 394), Tuple.Create(";color:red", 394), true)
);

WriteLiteral(" id=\"sfCacheDisable\"");

WriteLiteral(">Disable</a>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 449), Tuple.Create("\"", 504)
            
            #line 11 "..\..\Cache\Views\Statistics.cshtml"
, Tuple.Create(Tuple.Create("", 456), Tuple.Create<System.Object, System.Int32>(Url.Action((CacheController pc) => pc.Enable())
            
            #line default
            #line hidden
, 456), false)
);

WriteLiteral(" class=\"sf-button btn btn-default\"");

WriteAttribute("style", Tuple.Create("\r\n           style=\"", 539), Tuple.Create("\"", 611)
            
            #line 12 "..\..\Cache\Views\Statistics.cshtml"
, Tuple.Create(Tuple.Create("", 559), Tuple.Create<System.Object, System.Int32>(CacheLogic.GloballyDisabled ? "" : "display:none"
            
            #line default
            #line hidden
, 559), false)
);

WriteLiteral(" id=\"sfCacheEnable\"");

WriteLiteral(">Enable</a>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 654), Tuple.Create("\"", 708)
            
            #line 13 "..\..\Cache\Views\Statistics.cshtml"
, Tuple.Create(Tuple.Create("", 661), Tuple.Create<System.Object, System.Int32>(Url.Action((CacheController pc) => pc.Clean())
            
            #line default
            #line hidden
, 661), false)
);

WriteLiteral(" class=\"sf-button btn btn-default\"");

WriteLiteral(" id=\"sfCacheClear\"");

WriteLiteral(">Clean </a>\r\n    </div>\r\n    <table");

WriteLiteral(" class=\"table table-condensed\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>
                    Table
                </th>
                <th>
                    Type
                </th>
                <th>
                    Count
                </th>
                <th>
                    Hits
                </th>
                <th>
                    Invalidations
                </th>
                <th>
                    Loads
                </th>
                <th>
                    LoadTime
                </th>
            </tr>
        </thead>
        <tbody>


");

WriteLiteral("\r\n");

            
            #line 82 "..\..\Cache\Views\Statistics.cshtml"
            
            
            #line default
            #line hidden
            
            #line 82 "..\..\Cache\Views\Statistics.cshtml"
             foreach (var table in Model)
            {
                
            
            #line default
            #line hidden
            
            #line 84 "..\..\Cache\Views\Statistics.cshtml"
           Write(ShowTree(table, 0));

            
            #line default
            #line hidden
            
            #line 84 "..\..\Cache\Views\Statistics.cshtml"
                                   
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n    <script>\r\n        $(function () {\r\n");

WriteLiteral("            ");

            
            #line 90 "..\..\Cache\Views\Statistics.cshtml"
        Write(CacheClient.Model["init"]());

            
            #line default
            #line hidden
WriteLiteral(";\r\n        });\r\n    </script>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
